config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :buyerinfos
      resources :contacts
      resources :products
      resources :users
      resources :sellers
      resources :buyers
      resources :carts
      resources :categories
      resources :comments
      resources :line_items
      resources :orders
      resources :sellerinfos
      root to: "buyerinfos#index"
    end
  get 'comments/index'
  get 'comments/new'
  resources :orders
  resources :line_items
  resources :carts
  devise_for :sellers
  resources :sadmin , only: [:index]
  get 'sadmin/products' => "sadmin#listproducts"
  get 'sadmin/products/new' =>"sadmin#newproduct"
  get 'sadmin/orders' =>"sadmin#listorders"

  devise_for :buyers
  resources :products do
    resources :comments
  end
  resources :buyerinfos
  resources :sellerinfos
  get '/login'=> "sessions#new", as:"login"

  get 'sessions/create'
  get'sessions/new'
  get 'sessions/destroy'

  resources :users
  resources :contacts ,only: [:new, :create,:index]

  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/guide'

  get 'static_pages/signup'

  get 'static_pages/login'

  root 'static_pages#home'

end

app/models/buyer.rb
class Buyer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_one :buyerinfo
end

app/models/buyerinfo.rb
class Buyerinfo < ActiveRecord::Base
 # attr_accessor :phone, :fname, :lname, :address

  belongs_to :buyer
  validates :phone, :fname , :lname, :address , presence: true
  validates validates_numericality_of :phone
  validates :phone, length: {is: 12}
  enum gender: {
      "Male" => 0,
      "Female" => 1,

  }
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end
def total_price
  line_items.to_a.sum{|item| item.total_price}
end
end

app/models/category.rb
class Category < ApplicationRecord
  attr_accessor :type
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :commentable, polymorphic:  true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
validates :first_name,:last_name,:email,:phone_number,:context , presence: true
validates :email, format: { with: Devise.email_regexp, message: "invalid email" }
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order , optional: true
  belongs_to :product
  belongs_to :cart

  #calculate the price by multiplying the price of a unit by the quantity
  def total_price
    product.price*quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items , dependent: :destroy
  enum pay_type: {
      "Credit Card" => 0,
       "Pay On Arrival" => 1,
      "Fawry"=> 2
  }
  validates :name , :address , :email , presence: true
  validates :pay_type , inclusion: pay_types.keys

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id=nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessor :image


  belongs_to :seller
  has_many :line_items
  has_many :comments, as: :commentable
  #defining action to do before the deletion of a product by a seller
  before_destroy :ensure_not_referenced_by_any_line_item

  mount_uploader :image, ImageUploader
  validates :price,:name , presence: true
  validates_numericality_of :price

  #makes sure there are no current orders of the item wanted to be deleted
private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
       errors.add(:base, 'Line Items present')
       throw :abort
       end
  end
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable
  has_many :products
  has_one :sellerinfo
end

app/models/sellerinfo.rb
class Sellerinfo < ApplicationRecord
  belongs_to :seller
  validates  :first_name, :last_name,:address, :phone_number,:city, :gender, presence: true
  validates_numericality_of :phone_number
  validates :phone_number, length: {is: 12}
  enum gender: {
      "Male" => 0,
      "Female" => 1,

  }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
 layout 'static'

  def home
  end

  def about
  end

  def guide
  end

  def signup
  end

  def login
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sadmin_helper.rb
module SadminHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/_navigation.html.erb
<div class="row">
<div class="NavigationBar container" id="NavY">
  <nav>
    <div class="logo">
      <a href="/"><%= image_tag 'logo3.png'%></a>
    </div>

    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", static_pages_about_path %>
        <!--<ul>
                <li><a href="About.html/#What_is_Yadawy?">What is Yadawy?</a></li>
                <li><a href="#OurTeam">Out Team</a></li>
                <li><a href="#Mission">Mission</a></li>
        </ul>-->
      </li>
      <li><%= link_to "Products", products_path %></li>
      <li><a href="#">Brands</a></li>
      <li><%= link_to "Contact Us", new_contact_path %></li>
      <% if buyer_signed_in? %>
        <li >  <%=fa_icon "shopping-cart 9x" , class: " fas fa-shopping-cart fa-3x" , style: "color:brown; margin: 20px"%></li>

        <li> <%= link_to current_buyer.buyerinfo do %> <%= image_tag 'randomavatar.png',size:'70x70' %><% end  %></li>
        <li><%= link_to "Logout",destroy_buyer_session_path, method: :delete %></li>
      <%elsif seller_signed_in? %>

          <li>  <%= content_tag :span, "   ", class:"fa fa-envelope fa-2x"  %></li>
        <li>
        <%= content_tag :span, "   ", class:"fa fa-bullhorn fa-2x" , :style=>"color:black" %>
        </li>

        <li>  <%= image_tag 'randomavatar.png',size:'60x60' %></li>
        <li><%= link_to "Logout",destroy_seller_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "Log in" ,"#popup1", class:"active login-btn", method: :get%></li>
        <div id="popup1" class="overlay">
          <div class="popup">
            <h2>Hello There!</h2>
            <a class="close" href="">&times;</a>
            <div class="content">
              <ul>
             <li style="margin: 25px;"> <h4>Do you want to login in as a <span><%= button_to "Buyer", new_buyer_session_path ,class:"btn btn-danger",style:"width:auto;float:right " , method: :get%></span></h4></li>
             <li style="margin: 25px;">  <h4> Or do you want to login in as a <span><%= button_to "Seller", new_seller_session_path , class:"btn btn-warning",style:"width:auto;float:right", method: :get %></span></h4></li>
              </ul>
            </div>
          </div>
        </div>
      </li>
        <li><%= link_to "Sign Up" ,"#popup2", class:"active login-btn", method: :get%></li>
        <div id="popup2" class="overlay">
          <div class="popup">
            <h2>Hello There!</h2>
            <a class="close" href="">&times;</a>
            <div class="content">
              <ul>
                <li style="margin: 25px;"> <h4>Do you want to Sign Up in as a <span><%= button_to "Buyer", new_buyer_registration_path ,class:"btn btn-danger",style:"width:auto;float:right " , method: :get%></span></h4></li>
                <li style="margin: 25px;">  <h4> Or do you want to Sign Up in as a <span><%= button_to "Seller", new_seller_registration_path , class:"btn btn-warning",style:"width:auto;float:right", method: :get %></span></h4></li>
              </ul>
            </div>
          </div>
        </div>
        </li>
      <li><a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a></li>
    <% end  %>
    </ul>

  </nav>
</div>
</div>

app/views/static_pages/about.html.erb
<header class="v-header container">



  <div class="header-overlay"></div>

  <div class="header-content">
    <h1>Welcome to Yadawy.com</h1>
    <p>
      The first Egyptian online website to bring all the handmade products and services to the lights.
    </p>

  </div>

</header>

<div>
  <nav style="position:absolute; z-index:4; top:595px; background-color:rgb(245, 209, 156);">
    <ul style="float: none; padding-left: 330px;">
      <li><a href="#What_is_Yadawy?">What is Yadawy?</a></li>
      <li><a href="#OurTeam">Out Team</a></li>
      <li><a href="#Mission">Mission</a></li>
    </ul>
  </nav>
</div>
</br>

<script type="text/javascript">
    var slideIndex=1;

    showVideo(slideIndex);
    setInterval(nextSlide, 10000);

    function nextSlide(){
        var slide= document.getElementsByClassName("fullscreen-video-wrap");
        if (slideIndex>=slide.length) {slideIndex=0};
        slideIndex++;
        showVideo(slideIndex);
    }

    function currentSlide(n){
        showVideo(slideIndex=n);
    }

    function showVideo(n){
        var slide= document.getElementsByClassName("fullscreen-video-wrap");
        var dots= document.getElementsByClassName("dots");

        if (n>slide.length){slideIndex=1};
        if (n<1) {slideIndex= slide.length};

        for (var i=0; i<slide.length; i++)
        {
            slide[i].style.display= "none";
        };
        slide[slideIndex-1].style.display="block";

        for (var i=0; i<dots.length; i++)
        {
            dots[i].className= dots[i].className.replace(" active", "");
        };
        dots[slideIndex-1].className += " active";
    }
</script>
</br>
</br>
<section class="section section-c" style="background:white;">
  <div class="container">
    <h1 id="About" text-align:left style="color:rgb(0, 0, 0);">About Yadawy?</h1>
    <h3 id= "What_is_Yadawy?"align="left" style="color:rgb(0, 0, 0);">What is Yadawy?</h3>
    <p align="left" style="color:rgb(43, 41, 41);">
      Yadawy is an online website which serves both sellers and buyers to reach each other. As we know, the Egyptian community is a creative and productive one, many citizens excel
      at more than one profession, and Egyptian mothers specifically possess an arsenal of
      talent. The problem with the handmade industry, is that it’s hard to scale it and grow. It
      usually spreads with a word of mouth and nothing else. It’s not easy to start a website
      or a blog and maintain, as it requires constant monitoring, hosting and maintenance and
      many other things. Our goal then, is to help people start their businesses and connect
      them with buyers who might potentially be in great need of their products.
    </p>

    <h3 id="OurTeam"align="left" style="color:rgb(0, 0, 0);">Our Team</h3>
    <p align="left" style="color:rgb(43, 41, 41);">
      Our team is a group of professional programmers that will guarantee the privacy and the security of all your accounts. They is no need for a credit card as the payment is in cash. Our team is constantly working to assure the are no spams and to provide you with all the handmade products you can't find, or to helo you sell all the handmade products you're creating.
    </p>

    <h3 id="Mission"align="left" style="color:rgb(0, 0, 0);">Mission</h3>
    <p align="left" style="color: rgb(43, 41, 41);">
      Our mission is to help buyers and sellers to communicate, creating opportunities for both of them to get the best chances. This application is a commerce platform for buying and selling handmade products by
      directly connecting the customers with the craftsmen. Artists and craftsmen put their
      products up for sale and add each product’s details (material, price, availability, etc.).
      Customers can search for the products they want, compare different products and place
      orders. They can also review the product and/or the craftsmen after receiving their
      order. Craftsmen ship their products through one of the shipping agencies registered on
      the application.
      In the second section of the website, people will be able to showcase their services for
      selling ( drivers, plumbers, cooks, etc…) and and hourly or monthly rate and buyers will
      be able to get in touch directly with the sellers or hire them through the website.
    </p>
  </div>
</section>

<section class="section section-b">
  <h6>Copyright © 2018 Yadawy Inc. All rights reserved.</h6>
</section>

app/views/static_pages/guide.html.erb
<h1>StaticPages#guide</h1>
<p>Find me in app/views/static_pages/guide.html.erb</p>

app/views/static_pages/home.html.erb
 <header class="v-header container">




        <div class="header-overlay"></div>

        <div class="header-content">
             <h1>Welcome to Yadawy.com</h1>
             <p>
                  The first Egyptian online website to bring all the handmade products and services to the lights.
             </p>
             <a href="#Why_Yadawy?" class="btnw">Read More</a>


        </div>
 
    </header>

    <script>
            /* Toggle between adding and removing the "responsive" class to topnav when the user clicks on the icon */
              function myFunction() {
              var x = document.getElementById("Nav1");
              if (x.className === "NavigationBar") {
                  x.className += " responsive";
              } else {
                  x.className = "NavigationBar";
              }
          }
    </script>

    <br/>
    <div style="text-align: center;">
        <span class="dots" onclick=currentSlide(1)></span>
        <span class="dots" onclick=currentSlide(2)></span>
        <span class="dots" onclick=currentSlide(3)></span>
    </div>

    <script type="text/javascript">
    var slideIndex=1;
    
    showVideo(slideIndex);
    setInterval(nextSlide, 10000);

    function nextSlide(){
        var slide= document.getElementsByClassName("fullscreen-video-wrap");
        if (slideIndex>=slide.length) {slideIndex=0};
        slideIndex++;
        showVideo(slideIndex);
    }

    function currentSlide(n){
        showVideo(slideIndex=n);
    }

    function showVideo(n){
        var slide= document.getElementsByClassName("fullscreen-video-wrap");
        var dots= document.getElementsByClassName("dots");
       
        if (n>slide.length){slideIndex=1};
        if (n<1) {slideIndex= slide.length};

        for (var i=0; i<slide.length; i++)
        {
            slide[i].style.display= "none";
        };
        slide[slideIndex-1].style.display="block";
           
        for (var i=0; i<dots.length; i++)
        {
            dots[i].className= dots[i].className.replace(" active", "");
        };
        dots[slideIndex-1].className += " active";  
    }
    </script>

    <section class="section section-a">
        <div class="container">
            <h1>Yadawy App Soon!</h1>
            <p>
                    As mobile apps are better and faster, we are happily announcing that soon you'll be able to download Yadawy App for for all Android devices. This way, it'll be easier for you to buy all the handmade products you love whenever you want them. Or, you'll be able to upload all your products once you're done with them!
            </p>
        </div>
    </section>

    <section class="section section-c">
            <div class="container">
                <h1 id="Why_Yadawy?" text-align:left>Why choose Yadwy for your business?</h1>
                <h3 align="left" style="color:rgb(192, 188, 188);">Make The coolest Products</h3>
                <p align="left">
                        Our website supports all types of cool handmahe best products out there and shoot for the stars. the sky's the limit. We want to offer the biggest selection of handmade products in the world and that can only be done through the top notch crafters like yourself. This is your oppurunity to get to the big stage and steal the lights with the best you can think of. We make it easy to create all sort of brands for all sorts of businesses.
                
                </p>
                <h3 align="left" style="color:rgb(192, 188, 188);">Sell Your Products</h3>
                <p align="left">
                        Through an access to a huge base of custom oducts to thousands of interested buyers or get highered and get payed for your service. done through the top notch crafters like yourself. This is your oppurunity to get to the big stage and steal the lights with the best you can think of. We make it easy to create all sort of brands for all sorts of businesses. Add a selection of your finest products or offer a service to create custo
                </p>
                <h3 align="left" style="color:rgb(192, 188, 188);">Make A Fortune</h3>
                <p align="left">
                        Our website supports all types of cool handmade products. We want to help people to get to the big stage and steal the lights with the best you can think of. We make it easy to create all sort of brands for all sorts of businesses. Add a selection of your finest products or offer a service to create custom ones, group products under selections and
                </p>
            </div>
    </section>

    <section class="section section-b">
            <h6>Copyright © 2018 Yadawy Inc. All rights reserved.</h6>       
    </section>

app/views/static_pages/login.html.erb
<h1>StaticPages#login</h1>
<p>Find me in app/views/static_pages/login.html.erb</p>

app/views/static_pages/signup.html.erb
<h1>StaticPages#signup</h1>
<p>Find me in app/views/static_pages/signup.html.erb</p>