config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :buyerinfos
      resources :contacts
      resources :products
      resources :users
      resources :sellers
      resources :buyers
      resources :carts
      resources :categories
      resources :comments
      resources :line_items
      resources :orders
      resources :sellerinfos
      root to: "buyerinfos#index"
    end
  get 'comments/index'
  get 'comments/new'
  resources :orders
  resources :line_items
  resources :carts
  devise_for :sellers
  resources :sadmin , only: [:index]
  get 'sadmin/products' => "sadmin#listproducts"
  get 'sadmin/products/new' =>"sadmin#newproduct"
  get 'sadmin/orders' =>"sadmin#listorders"

  devise_for :buyers
  resources :products do
    resources :comments
  end
  resources :buyerinfos
  resources :sellerinfos
  get '/login'=> "sessions#new", as:"login"

  get 'sessions/create'
  get'sessions/new'
  get 'sessions/destroy'

  resources :users
  resources :contacts ,only: [:new, :create,:index]

  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/guide'

  get 'static_pages/signup'

  get 'static_pages/login'

  root 'static_pages#home'

end

app/models/buyer.rb
class Buyer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_one :buyerinfo
end

app/models/buyerinfo.rb
class Buyerinfo < ActiveRecord::Base
 # attr_accessor :phone, :fname, :lname, :address

  belongs_to :buyer
  validates :phone, :fname , :lname, :address , presence: true
  validates validates_numericality_of :phone
  validates :phone, length: {is: 12}
  enum gender: {
      "Male" => 0,
      "Female" => 1,

  }
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end
def total_price
  line_items.to_a.sum{|item| item.total_price}
end
end

app/models/category.rb
class Category < ApplicationRecord
  attr_accessor :type
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :commentable, polymorphic:  true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
validates :first_name,:last_name,:email,:phone_number,:context , presence: true
validates :email, format: { with: Devise.email_regexp, message: "invalid email" }
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order , optional: true
  belongs_to :product
  belongs_to :cart

  #calculate the price by multiplying the price of a unit by the quantity
  def total_price
    product.price*quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items , dependent: :destroy
  enum pay_type: {
      "Credit Card" => 0,
       "Pay On Arrival" => 1,
      "Fawry"=> 2
  }
  validates :name , :address , :email , presence: true
  validates :pay_type , inclusion: pay_types.keys

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id=nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessor :image


  belongs_to :seller
  has_many :line_items
  has_many :comments, as: :commentable
  #defining action to do before the deletion of a product by a seller
  before_destroy :ensure_not_referenced_by_any_line_item

  mount_uploader :image, ImageUploader
  validates :price,:name , presence: true
  validates_numericality_of :price

  #makes sure there are no current orders of the item wanted to be deleted
private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
       errors.add(:base, 'Line Items present')
       throw :abort
       end
  end
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable
  has_many :products
  has_one :sellerinfo
end

app/models/sellerinfo.rb
class Sellerinfo < ApplicationRecord
  belongs_to :seller
  validates  :first_name, :last_name,:address, :phone_number,:city, :gender, presence: true
  validates_numericality_of :phone_number
  validates :phone_number, length: {is: 12}
  enum gender: {
      "Male" => 0,
      "Female" => 1,

  }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/admin/carts_controller.rb
module Admin
  class CartsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Cart.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Cart.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  layout 'cart'
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/buyerinfos_helper.rb
module BuyerinfosHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sadmin_helper.rb
module SadminHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice alert alert-info"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
  <aside id=“notice alert alert-info”><%= notice %></aside>
<% end %>
<div class="wrap cf">
  <h1 class="projTitle">The Beauty Behind <span>Pro-</span>ducts</h1>
  <div class="heading cf">
    <h1>My Yadawy Cart</h1>

    <%= link_to "Continue Shopping", products_path, class:"continue" %>
  </div>

<div class="cart">
<ul class="cartWrap">
  <% @cart.line_items.each do |item| %>

      <li class="items <%=cycle('even','odd')%>">

        <div class="infoWrap">
          <div class="cartSection">
            <img src="http://lorempixel.com/output/technics-q-c-300-300-4.jpg" alt="" class="itemImg" />
            <p class="itemNumber"><%= item.id %></p>
            <h3><%= item.product.name %></h3>

            <p class="qty"> <%= item.quantity   %> &times; <%= number_to_currency(item.product.price)%></p>



          <div style="float: right;">
              <div class="prodTotal cartSection">
                <p style=""><%= number_to_currency(item.total_price) %></p>
              </div>
              <div class="cartSection removeWrap">
                <a href="#" class="remove">x</a>
                <%= link_to "x", item ,class:"remove", method: :delete %>
              </div>
          </div>
        </div>
        </div>
      </li>

  <% end %>
</ul>
  <div class="promoCode"><label for="promo">Have A Promo Code?</label><input type="text" name="promo" placholder="Enter Code" />
    <a href="" class="btn"></a></div>

  <div class="subtotal cf">
    <ul>



      <li class="totalRow final"><span class="label">Total</span><span class="value"><%= number_to_currency(@cart.total_price)%></span></li>
      <li class="totalRow"><%= button_to 'Checkout' , new_order_path, method: :get, class:"checkout btn continue" %></li>
      <li><%= button_to 'Empty cart', @cart, method: :delete,class:"checkout btn continue", data: { confirm: 'Are you sure?' } %></li>
    </ul>
  </div>
</div>

</div>