config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :buyerinfos
      resources :contacts
      resources :products
      resources :users
      resources :sellers
      resources :buyers
      resources :carts
      resources :categories
      resources :comments
      resources :line_items
      resources :orders
      resources :sellerinfos
      root to: "buyerinfos#index"
    end
  get 'comments/index'
  get 'comments/new'
  resources :orders
  resources :line_items
  resources :carts
  devise_for :sellers
  resources :sadmin , only: [:index]
  get 'sadmin/products' => "sadmin#listproducts"
  get 'sadmin/products/new' =>"sadmin#newproduct"
  get 'sadmin/orders' =>"sadmin#listorders"

  devise_for :buyers
  resources :products do
    resources :comments
  end
  resources :buyerinfos
  resources :sellerinfos
  get '/login'=> "sessions#new", as:"login"

  get 'sessions/create'
  get'sessions/new'
  get 'sessions/destroy'

  resources :users
  resources :contacts ,only: [:new, :create,:index]

  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/guide'

  get 'static_pages/signup'

  get 'static_pages/login'

  root 'static_pages#home'

end

app/models/buyer.rb
class Buyer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_one :buyerinfo
end

app/models/buyerinfo.rb
class Buyerinfo < ActiveRecord::Base
 # attr_accessor :phone, :fname, :lname, :address

  belongs_to :buyer
  validates :phone, :fname , :lname, :address , presence: true
  validates validates_numericality_of :phone
  validates :phone, length: {is: 12}
  enum gender: {
      "Male" => 0,
      "Female" => 1,

  }
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end
def total_price
  line_items.to_a.sum{|item| item.total_price}
end
end

app/models/category.rb
class Category < ApplicationRecord
  attr_accessor :type
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :commentable, polymorphic:  true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
validates :first_name,:last_name,:email,:phone_number,:context , presence: true
validates :email, format: { with: Devise.email_regexp, message: "invalid email" }
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order , optional: true
  belongs_to :product
  belongs_to :cart

  #calculate the price by multiplying the price of a unit by the quantity
  def total_price
    product.price*quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items , dependent: :destroy
  enum pay_type: {
      "Credit Card" => 0,
       "Pay On Arrival" => 1,
      "Fawry"=> 2
  }
  validates :name , :address , :email , presence: true
  validates :pay_type , inclusion: pay_types.keys

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id=nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessor :image


  belongs_to :seller
  has_many :line_items
  has_many :comments, as: :commentable
  #defining action to do before the deletion of a product by a seller
  before_destroy :ensure_not_referenced_by_any_line_item

  mount_uploader :image, ImageUploader
  validates :price,:name , presence: true
  validates_numericality_of :price

  #makes sure there are no current orders of the item wanted to be deleted
private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
       errors.add(:base, 'Line Items present')
       throw :abort
       end
  end
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable
  has_many :products
  has_one :sellerinfo
end

app/models/sellerinfo.rb
class Sellerinfo < ApplicationRecord
  belongs_to :seller
  validates  :first_name, :last_name,:address, :phone_number,:city, :gender, presence: true
  validates_numericality_of :phone_number
  validates :phone_number, length: {is: 12}
  enum gender: {
      "Male" => 0,
      "Female" => 1,

  }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/sellerinfos_controller.rb
class SellerinfosController < ApplicationController
  before_action :set_sellerinfo, only: [:show, :edit, :update, :destroy]

  skip_before_action :complete_sign_up
  # GET /sellerinfos
  # GET /sellerinfos.json
  def index
    @sellerinfos = Sellerinfo.all
  end

  # GET /sellerinfos/1
  # GET /sellerinfos/1.json
  def show
  end

  # GET /sellerinfos/new
  def new
    @sellerinfo = Sellerinfo.new
  end

  # GET /sellerinfos/1/edit
  def edit
  end

  # POST /sellerinfos
  # POST /sellerinfos.json
  def create
    @sellerinfo = Sellerinfo.new(sellerinfo_params)
    @sellerinfo.seller_id=current_seller.id
    respond_to do |format|
      if @sellerinfo.save
        format.html { redirect_to @sellerinfo, notice: 'Sellerinfo was successfully created.' }
        format.json { render :show, status: :created, location: @sellerinfo }
      else
        format.html { render :new }
        format.json { render json: @sellerinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellerinfos/1
  # PATCH/PUT /sellerinfos/1.json
  def update
    respond_to do |format|
      if @sellerinfo.update(sellerinfo_params)
        format.html { redirect_to @sellerinfo, notice: 'Sellerinfo was successfully updated.' }
        format.json { render :show, status: :ok, location: @sellerinfo }
      else
        format.html { render :edit }
        format.json { render json: @sellerinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellerinfos/1
  # DELETE /sellerinfos/1.json
  def destroy
    @sellerinfo.destroy
    respond_to do |format|
      format.html { redirect_to sellerinfos_url, notice: 'Sellerinfo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sellerinfo
      @sellerinfo = Sellerinfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def sellerinfo_params
    params.require(:sellerinfo).permit( :first_name,:last_name,:phone_number,:city,:address,:image, :gender)
  end
end

app/helpers/buyerinfos_helper.rb
module BuyerinfosHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sadmin_helper.rb
module SadminHelper
end

app/helpers/sellerinfos_helper.rb
module SellerinfosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sellerinfos/_form.html.erb
<%= form_for(@sellerinfo, :html =>{:multipart=> true}) do |f| %>
  <% if @sellerinfo.errors.any? %>
    <div id="error_explanation">
      <h2 style="color:red"><%= pluralize(@sellerinfo.errors.count, "error") %> prohibited this sellerinfo from being saved:</h2>

      <ul>
        <% @sellerinfo.errors.full_messages.each do |message| %>
          <li style="color:red"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="infofield">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="infofield">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="infofield">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.select :gender , Sellerinfo.genders.keys,
                 prompt: 'Select your gender' %>
  </div>
  <div class="infofield">
    <%= f.label :phone_number %><br>
    <%= f.telephone_field :phone_number %>
  </div>
  <div class="infofield">
    <%= f.label :city %><br>
    <%= f.text_field :city %>

  </div>
  <div class="actions">
    <%= f.submit "Update my info", class:"btn"%>
  </div>
<% end %>

app/views/sellerinfos/edit.html.erb
<h1>Editing Sellerinfo</h1>

<%= render 'form', sellerinfo: @sellerinfo %>

<%= link_to 'Show', @sellerinfo %> |
<%= link_to 'Back', sellerinfos_path %>

app/views/sellerinfos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sellerinfos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sellerinfos.each do |sellerinfo| %>
      <tr>
        <td><%= link_to 'Show', sellerinfo %></td>
        <td><%= link_to 'Edit', edit_sellerinfo_path(sellerinfo) %></td>
        <td><%= link_to 'Destroy', sellerinfo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sellerinfo', new_sellerinfo_path %>

app/views/sellerinfos/new.html.erb
<div class="infocontainer form-control ">
  <h1 class="infofield">Complete your profile to Get your journey Started!</h1>
  <h5 class="infofield">Created hundreds of cool products! get Started now:</h5>

<%= render 'form', sellerinfo: @sellerinfo %>

<%= link_to 'Back', sellerinfos_path %>
</div>

app/views/sellerinfos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sellerinfo_path(@sellerinfo) %> |
<%= link_to 'Back', sellerinfos_path %>