config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :buyerinfos
      resources :contacts
      resources :products
      resources :users
      resources :sellers
      resources :buyers
      resources :carts
      resources :categories
      resources :comments
      resources :line_items
      resources :orders
      resources :sellerinfos
      root to: "buyerinfos#index"
    end
  get 'comments/index'
  get 'comments/new'
  resources :orders
  resources :line_items
  resources :carts
  devise_for :sellers
  resources :sadmin , only: [:index]
  get 'sadmin/products' => "sadmin#listproducts"
  get 'sadmin/products/new' =>"sadmin#newproduct"
  get 'sadmin/orders' =>"sadmin#listorders"

  devise_for :buyers
  resources :products do
    resources :comments
  end
  resources :buyerinfos
  resources :sellerinfos
  get '/login'=> "sessions#new", as:"login"

  get 'sessions/create'
  get'sessions/new'
  get 'sessions/destroy'

  resources :users
  resources :contacts ,only: [:new, :create,:index]

  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/guide'

  get 'static_pages/signup'

  get 'static_pages/login'

  root 'static_pages#home'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessor :image


  belongs_to :seller
  has_many :line_items
  has_many :comments, as: :commentable
  #defining action to do before the deletion of a product by a seller
  before_destroy :ensure_not_referenced_by_any_line_item

  mount_uploader :image, ImageUploader
  validates :price,:name , presence: true
  validates_numericality_of :price

  #makes sure there are no current orders of the item wanted to be deleted
private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
       errors.add(:base, 'Line Items present')
       throw :abort
       end
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Product.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Product.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_seller!, only:[:new, :create]
  before_action :recommended, only: [:show]
  # GET /products
  # GET /products.json
  def index
    @products = Product.where(["name LIKE ?","%#{params[:search]}%" ])
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @commentable=@product
    @comments=@commentable.comments
    @comment=Comment.new
  end

  # GET /products/new
  def new

    @product = Product.new

  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.seller_id=current_seller.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :category,:price, :seller, :specs, :image)
    end
    def recommended
      #selects similar products by selecting the orders where a certain product exists than indexing products bought on the same purchase
      product_id=@product.id

      arr=[]
      temp=[]
      lines=LineItem.joins(:order,:product)
      orders=lines.where("product_id=#{product_id}").select("order_id")
      if orders
      orders.each {|k| arr.push(k[:order_id])}
      jointproducts =lines.where("order_id IN (#{arr.join(',')})")
      similar_products=jointproducts.where("product_id != #{product_id}" )
       if similar_products
         similar_products.each {|k| temp.push(k[:product_id]) }
         @similar_p=Product.where("id IN (#{temp.join(',')})").limit(3)
       end
      end

    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, :html =>{:multipart=> true} ) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :specs %><br>
    <%= f.text_field :specs %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%@product.seller= current_seller  %>
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_new.html.erb
<h1>New Product</h1>

<%= render '/products/form' %>

<%= link_to 'Back', products_path %>

app/views/products/_products.html.erb
<div class="card-deck">
  <div class="card-columns">
  <% @products.each do |product| %>


    <div class="card">
      <div class="">
        <% if product.image? %>
          <%= image_tag product.image.url(:productimage),class: "card-img-top",size:"204x204" %>
        <% else %>
          <%= image_tag 'No_Image_Available.jpg',class: "card-img-top",size:"204x204" %>
        <%end %>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <%= sanitize(product.specs) %>
          <div class="price card-text">
            <h3><%= number_to_currency(product.price) %></h3>

          </div>
        </div>

        <div class="card-footer">
          <span><%= button_to 'Add to Cart', line_items_path(product_id: product),class:"btn btn-primary" ,style:"width:auto;float:left;margin: 0 30px 0 30px"%></span>
          <span>  <%= button_to 'show',  product , class:"btn btn-info",:method => :get,style:"width:auto;"%></span>
        </div>
      </div>
    </div>
  <% end %>

</div>
</div>

app/views/products/_recommended.html.erb
<div class="card-deck">

  <% @similar_p.each do |product| %>


    <div class="card">
      <div class="">
        <% if product.image? %>
          <%= image_tag product.image.url(:productimage),class: "card-img-top",size:"204x204" %>
        <% else %>
          <%= image_tag 'No_Image_Available.jpg',class: "card-img-top",size:"204x204" %>
        <%end %>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <%= sanitize(product.specs) %>
          <div class="price card-text">
            <h3><%= number_to_currency(product.price) %></h3>

          </div>
        </div>

        <div class="card-footer">
          <span><%= button_to 'Add to Cart', line_items_path(product_id: product),class:"btn btn-primary" ,style:"width:auto;float:left;margin: 0 30px 0 30px"%></span>
          <span>  <%= button_to 'show',  product , class:"btn btn-info",:method => :get,style:"width:auto;"%></span>
        </div>
      </div>
    </div>

  <% end %>

</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', product_path %>

app/views/products/index.html.erb
<p id="notice "><%= notice  %></p>
<div class="">
  <%= image_tag 'searchpagel.jpg',class:"img-fluid" %>
</div>
<%= form_tag products_path, :method =>'get' do %>
 <div class=" searchcontainer ">
   <div class="row">
      <div class="input-group mb-3 col-6">
      <%=text_field_tag :search, params[:search], class:"form-control", type:"text" %>

      </div>
      <div class="col-auto">
      <%= submit_tag "Search", class:"btnw btn-primary" %>
      </div>
    </div>
 </div>
<% end  %>



  <div class="card-deck">
    <div class="card-columns">


    <% @products.each do |product| %>


      <div class="card">
        <div class="">
        <% if product.image? %>
          <%= image_tag product.image.url(:productimage),class: "card-img-top",size:"204x204" %>
        <% else %>
          <%= image_tag 'No_Image_Available.jpg',class: "card-img-top",size:"204x204" %>
        <%end %>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <%= sanitize(product.specs) %>
          <div class="price card=text">
          <h3><%= number_to_currency(product.price) %></h3>

        </div>
        </div>

        <div class="card-footer">
          <span><%= button_to 'Add to Cart', line_items_path(product_id: product),class:"btn btn-primary" ,style:"width:auto;float:left;margin: 0 30px 0 30px"%></span>
          <span>  <%= button_to 'show',  product , class:"btn btn-info",:method => :get,style:"width:auto;"%></span>
        </div>
      </div>
      </div>

    <% end %>
      </div>
  </div>


</table>

<br>

<%= link_to 'New Product', new_product_path %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/new.js.erb
$("#injector").html("<%=  render 'products/_new' %>")

app/views/products/show.html.erb
<p id="notice alert alert-info" ><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @product.seller %>
</p>

<p>
  <strong>Specs:</strong>
  <%= @product.specs %>
</p>

<p>
  <strong>Image:</strong>
  <%if @product.image? %>
  <%= image_tag @product.image.url(:thumb) if @product.image? %>
<% else %>
  <%= image_tag 'No_Image_Available.jpg', size:"204x204" %>
  <%end %>
</p>
<%= render "products/recommended"%>
<%= render "comments/comments" %>
<%= render "comments/form" %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', product_path %>